### ISSUE TITLE
The left right doesnt work 

### ISSUE THREAD

**Issue by TrevorXt** [mdejean/helitest#1]
Can you help me when i play, the left and right doesnt work and the heli flips upside down
I am a noob btw

**Comment by mdejean** [comment]
WASD + mouse are the controls.

**Comment by TrevorXt** [comment]
Yes, i tried WASD + mouse controls but its still not working any recommendation

**Comment by TrevorXt** [comment]
Heyyy, sorry for the incovinience the controls worked 
Last question can i use my own mess i made on this blueprint Will it work??
Thank youu
